name: Sample actions

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
​
13
  # Allows you to run this workflow manually from the Actions tab
14
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: arkb
        if: always()
        run: |
          curl https://anchor.fm/s/319a2820/podcast/rss --compressed >> arkb.xml && git add . && git commit -m "ci" && git push