name: Sample actions

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: arkb
        if: always()
        run: |
          curl https://anchor.fm/s/319a2820/podcast/rss --compressed >> arkb.xml && git add . && git commit -m "ci" && git push